services:
  - type: web
    name: python-with-java
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y openjdk-11-jdk
      pip install -r requirements.txt
    startCommand: python app.py
